function phikx = evalphik(k, a, b, alpha, beta, w, x)

%   EVALPHIK evaluates the kth orthogononal polynomials generated by the
%   3-term recurrence formula. 
%
%   phikx = evalphik(k, a, b, alpha, beta, w, x) returns values of the kth
%           polynomial at x.
%
%   See also:
%       getcoef.m, lscoef.m
%
%   Yulun Zeng, Oct, 2015

phikm = @(x) 1;
phik = @(x) x - integral(@(x)x.*1.*w(x),a,b)./integral(@(x)1.*1.*w(x),a,b);
phikmx = phikm(x);
phikx = phik(x);

if k > 1
    for i = 2:k
        phikpx = (x-alpha(i)).*phikx - beta(i).*phikmx;
        phikmx = phikx;
        phikx = phikpx;
    end
elseif k == 0
    phikx = phikmx;
end

end